### ISSUE TITLE
kjnjkn

### ISSUE THREAD

**Issue by Jo2m** [hdboye/FnfModAttempt#5]
**Mod name**
B-side
**Describe the bug**
For some reason, whenever I click on this or any mod to be exact, the tab just dies.
**To Reproduce**
1. Go to hdboye.github.io
2. Click on B-side
3. Scroll down to Story Mode

**Expected behavior**
It running
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Version:85.0.4183.133

**Additional context**

**Comment by hdboye** [comment]
Mod site wont be updated again
